version: 2
jobs:
  build:
    environment:
    docker: # run the steps with Docker
      - image: maven:3.6.3-openjdk-14
    steps: # a collection of executable commands
      - checkout # check out source code to working directory
      - run: mvn clean install
      - store_artifacts:
          path: target/

workflows:
  version: 2
  workflow:
    jobs:
      - build
